//
//  AuthModels.swift
//  LetsTell
//
//  Created by Павел Чернышев on 12.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI

enum Auth {
    // MARK: Use cases
    
    enum Login {
        struct Request {
            var login: String
            var password: String
        }
        struct Response {
            var succes: Bool
            var error: Error?
        }
        struct ViewModel {
            var loginSucces: Bool
            var errorMessage: String?
        }
    }
    
    enum LoginByToken {
        struct Request {
            var completion: (Bool) -> Void
        }
    }
}
