//
//  AuthPresenter.swift
//  LetsTell
//
//  Created by Павел Чернышев on 12.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI
import Alamofire

protocol AuthPresentationLogic {
  func presentLogin(response: Auth.Login.Response)
}

class AuthPresenter: AuthPresentationLogic {
  weak var viewController: AuthDisplayLogic?
  
  // MARK: Do something
  
  func presentLogin(response: Auth.Login.Response) {
    if response.succes {
        viewController?.displayLogin(viewModel: Auth.Login.ViewModel(loginSucces: response.succes, errorMessage: nil))
    } else {
        var errorMess = "something wrong"
        if let error = response.error as? ErrorList {
            errorMess = error.errors.first ?? errorMess
        } else if let error = response.error as? AFError {
            errorMess = error.localizedDescription
        }
        let viewModel = Auth.Login.ViewModel(loginSucces: response.succes, errorMessage: errorMess)
        viewController?.displayLogin(viewModel: viewModel)
    }
  }
}
