//
//  FeedDetailPresenter.swift
//  LetsTell
//
//  Created by Павел Чернышев on 19.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedDetailPresentationLogic {
  func presentStory(response: FeedDetail.Steps.Response)
}

class FeedDetailPresenter: FeedDetailPresentationLogic {
  weak var viewController: FeedDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentStory(response: FeedDetail.Steps.Response) {
    switch response.storySteps {
    case .success(let feedResponse):
        let viewModel = FeedDetail.Steps.ViewModel(steps: feedResponse.body, error: nil)
        viewController?.displaySteps(viewModel: viewModel)
    case .failure(let error):
        let viewModel = FeedDetail.Steps.ViewModel(steps: [], error: error.localizedDescription)
        viewController?.displaySteps(viewModel: viewModel)
    }
  }
}
