//
//  FeedDetailRouter.swift
//  LetsTell
//
//  Created by Павел Чернышев on 19.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FeedDetailRoutingLogic {
  // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FeedDetailDataPassing {
  var dataStore: FeedDetailDataStore? { get }
}

class FeedDetailRouter: NSObject, FeedDetailRoutingLogic, FeedDetailDataPassing {
  weak var viewController: FeedDetailViewController?
  var dataStore: FeedDetailDataStore?
  
  // MARK: Routing
  
  // func routeToSomewhere(segue: UIStoryboardSegue?)
  // {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  // }

  // MARK: Navigation
  
  // func navigateToSomewhere(source: FeedDetailViewController, destination: SomewhereViewController)
  // {
  //  source.show(destination, sender: nil)
  // }
  
  // MARK: Passing data
  
  // func passDataToSomewhere(source: FeedDetailDataStore, destination: inout SomewhereDataStore)
  // {
  //  destination.name = source.name
  // }
}
