//
//  FeedDetailModels.swift
//  LetsTell
//
//  Created by Павел Чернышев on 19.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FeedDetail {
  // MARK: Use cases
  
  enum Steps {
    struct Request {
        var story: Story
    }
    struct Response {
        var storySteps: NetworkResult<BodyResponse<[StoryStep]>, NSError>
    }
    struct ViewModel {
        var steps: [StoryStep]
        var error: String?
    }
  }
}
