//
//  ProfilePresenter.swift
//  LetsTell
//
//  Created by Павел Чернышев on 27.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentLogout(response: Profile.Logout.Response)
    func presentOwner(response: Profile.User.Response)
}

class ProfilePresenter: ProfilePresentationLogic {
    
    weak var viewController: ProfileDisplayLogic?
    
    // MARK: Do something
    
    func presentLogout(response: Profile.Logout.Response) {
        let viewModel = Profile.Logout.ViewModel(logout: response.logout)
        viewController?.displayLogout(viewModel: viewModel)
    }
    
    func presentOwner(response: Profile.User.Response) {
        let viewModel = Profile.User.ViewModel(name: response.owner.name, email: response.owner.email)
        viewController?.displayOwner(viewModel: viewModel)
    }
}
