//
//  ProfileModels.swift
//  LetsTell
//
//  Created by Павел Чернышев on 27.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
    // MARK: Use cases
    
    enum Logout {
        struct Request {
            var logout: Bool
        }
        struct Response {
            var logout: Bool
        }
        struct ViewModel {
            var logout: Bool
        }
    }
    
    enum User {
        struct Request {
            var load: Bool
        }
        struct Response {
            var owner: Owner
        }
        struct ViewModel {
            var name: String
            var email: String
        }
    }
}
