//
//  StoriesFilterModels.swift
//  LetsTell
//
//  Created by Павел Чернышев on 26.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ErrorMessage = String

enum StoriesFilter {
    
    enum Filters {
        struct Request {
            
        }
        struct Response {
            var filters: NetworkResult<[FilterSectionModel], NSError>
            var applyedFilters: [ApplyedFiltersStorageModel]
        }
        struct ViewModel {
            var filtersResult: PresenterResult<[FilterSectionModel], ErrorMessage>
        }
    }
    
    enum Applying {
        struct Request {
            var filters: [FilterSectionModel]
        }
        struct Response {
            var filersChanged: Bool
        }
        struct ViewModel {
            var filersChanged: Bool
        }
    }
    
}
