//
//  LoadingAppViewController.swift
//  LetsTell
//
//  Created by Павел Чернышев on 29.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SwiftUI
import UIKit

class LoadingAppViewController: ObservableObject {
    var authController: AuthViewController?
    
    private var currentlyLoading = false

    @Published var isLoaded = false
    
    // MARK: Setup
    public func setup(container: ObjectsGetter) {
        self.authController = container.getObject()
    }
    
    func checkToken() {
        if !currentlyLoading {
            currentlyLoading = true
            DispatchQueue.global().async {
                self.authController?.loginBySavedToken(completion: { success in
                    self.displayCheckedToken(viewModel: LoadingApp.CheckToken.ViewModel(success: success))
                })
            }
        }
    }
    
    func displayCheckedToken(viewModel: LoadingApp.CheckToken.ViewModel) {
        DispatchQueue.main.async {
            self.isLoaded = true
            self.currentlyLoading = false
        }
    }
}
