# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsTell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetsTell
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'Swinject'

  target 'LetsTellTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetsTellUITests' do
    # Pods for testing
  end

end
