//
//  FeedModels.swift
//  LetsTell
//
//  Created by Павел Чернышев on 02.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

enum Feed {
    enum Network {
        struct Request {
            var page: Int
        }
        struct Response {
            var feed: NetworkResult<FeedResponse, NSError>
        }
        struct ViewModel {
            var stories: [Story]
            var hasMoreStories: Bool
            var currentPage: Int
        }
    }
    
    enum StoryImage {
        struct Request {
            var stories: [Story]
        }
        struct Response {
            var story: Story
            var image: NetworkResult<UIImage, NSError>
        }
        struct ViewModel {
            var story: Story
            var image: UIImage?
        }
    }
}
